version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/employee_management
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
